# Generated by Django 5.1.6 on 2025-03-04 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('module_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('module_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('year', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ratings.module')),
                ('professors', models.ManyToManyField(to='ratings.professor')),
            ],
        ),
        migrations.CreateModel(
            name='CachedRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ratings.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('user', models.CharField(max_length=30)),
                ('module_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ratings.moduleinstance')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ratings.professor')),
            ],
        ),
    ]
